### ISSUE TITLE
请问 pixiv配置文件下如何编写多个token

### ISSUE THREAD

**Issue by airdm** [mixmoe/HibiAPI#398]
我现在写的方式为
![image](https://github.com/mixmoe/HibiAPI/assets/10095644/fbed81ab-a10f-49f8-8363-5014b5e018ff)
这样的格式会报错.我应该怎么设置.

**Comment by mnixry** [comment]
```yml
enabled: true

# HTTP代理地址
# 示例格式
# proxy: { "all://": "http://127.0.0.1:1081" }
proxy: {}

account:
  # Pixiv 登录凭证刷新令牌 (Refresh Token)
  # 获取方法请参考: https://github.com/mixmoe/HibiAPI/issues/53
  # 支持使用多个账户进行负载均衡, 每行一个token
  token: |
	token1
	token2
	token3

language: zh-cn # 返回语言, 会影响标签的翻译
```
